# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
"""
Auto-generated general models for the X API.

This module provides Pydantic models for request and response data structures
for the general endpoints of the X API. All models are generated
from the OpenAPI specification and provide type safety and validation.

Generated automatically - do not edit manually.
"""

from typing import Dict, List, Optional, Any, Union, Literal
from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime

# Type aliases for referenced schemas (defined as Any for flexibility)
# These allow models to reference types without requiring full schema definitions
Expansions = Any
Tweet = Any
User = Any
Space = Any
Community = Any
Media = Any
Poll = Any
Place = Any
XList = Any  # Avoid conflict with typing.List
DmEvent = Any
News = Any
Usage = Any
ComplianceJob = Any
ComplianceJobName = Any
RulesCount = Any
RulesResponseMetadata = Any
Rule = Any
MediaId = Any
MediaCategory = Any
MediaCategorySubtitles = Any
TweetId = Any
UserId = Any
CommunityId = Any
ListId = Any
SpaceId = Any
WebhookConfigId = Any
PublicKey = Any
FilteredStreamingTweetResponse = Any
TweetText = Any
TweetReplySettings = Any
SubtitleLanguage = Any
Subtitles = Any
SubtitleLanguageCode = Any


# Models for get_open_api_spec


class GetOpenApiSpecResponse(BaseModel):
    """Response model for get_open_api_spec"""

    model_config = ConfigDict(populate_by_name=True, extra="allow")
