# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
"""
Auto-generated search module for the X API.

This module provides access to the search endpoints of the X API
and serves as the main entry point for all search-related functionality.

Generated automatically - do not edit manually.
"""

from .client import SearchClient

__all__ = ["SearchClient"]
