# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
"""
Auto-generated compliance models for the X API.

This module provides Pydantic models for request and response data structures
for the compliance endpoints of the X API. All models are generated
from the OpenAPI specification and provide type safety and validation.

Generated automatically - do not edit manually.
"""

from typing import Dict, List, Optional, Any, Union, Literal
from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime


# Models for get_jobs


class GetJobsResponse(BaseModel):
    """Response model for get_jobs"""

    model_config = ConfigDict(populate_by_name=True, extra="allow")


# Models for create_jobs


class CreateJobsRequest(BaseModel):
    """Request model for create_jobs"""

    model_config = ConfigDict(populate_by_name=True)


class CreateJobsResponse(BaseModel):
    """Response model for create_jobs"""

    model_config = ConfigDict(populate_by_name=True, extra="allow")


# Models for get_jobs_by_id


class GetJobsByIdResponse(BaseModel):
    """Response model for get_jobs_by_id"""

    model_config = ConfigDict(populate_by_name=True, extra="allow")
