# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
"""
Auto-generated structural tests for {"class_name": "Mutes", "display_name": "mutes", "import_name": "mutes", "original": ["mutes"], "property_name": "mutes"} client.

This module contains tests that validate the structure and API surface
of the {"class_name": "Mutes", "display_name": "mutes", "import_name": "mutes", "original": ["mutes"], "property_name": "mutes"} client. These tests ensure that all expected methods
exist, have correct signatures, and proper type annotations for robust API contracts.

Generated automatically - do not edit manually.
"""

import pytest
import inspect
from typing import get_type_hints
from xdk.mutes.client import MutesClient
from xdk import Client


class TestMutesStructure:
    """Test the structure of MutesClient."""


    def setup_class(self):
        """Set up test fixtures."""
        # Provide all authentication types for comprehensive test coverage
        # Tests mock the session, so actual HTTP requests won't be made
        from xdk.oauth1_auth import OAuth1
        oauth1 = OAuth1(
            api_key="test_api_key",
            api_secret="test_api_secret",
            callback="http://localhost:8080/callback",
            access_token="test_access_token",
            access_token_secret="test_access_token_secret",
        )
        self.client = Client(
            base_url="https://api.example.com",
            bearer_token="test_bearer_token",
            access_token="test_access_token",
            auth=oauth1,
        )
        self.mutes_client = getattr(self.client, "mutes")


    def test_unmute_user_exists(self):
        """Test that unmute_user method exists with correct signature."""
        # Check method exists
        method = getattr(MutesClient, "unmute_user", None)
        assert method is not None, f"Method unmute_user does not exist on MutesClient"
        # Check method is callable
        assert callable(method), f"unmute_user is not callable"
        # Check method signature
        sig = inspect.signature(method)
        params = list(sig.parameters.keys())
        # Should have 'self' as first parameter
        assert len(params) >= 1, f"unmute_user should have at least 'self' parameter"
        assert (
            params[0] == "self"
        ), f"First parameter should be 'self', got '{params[0]}'"
        # Check required parameters exist (excluding 'self')
        required_params = [
            "source_user_id",
            "target_user_id",
        ]
        for required_param in required_params:
            assert (
                required_param in params
            ), f"Required parameter '{required_param}' missing from unmute_user"
        # Check optional parameters have defaults (excluding 'self')
        optional_params = []
        for optional_param in optional_params:
            if optional_param in params:
                param_obj = sig.parameters[optional_param]
                assert (
                    param_obj.default is not inspect.Parameter.empty
                ), f"Optional parameter '{optional_param}' should have a default value"


    def test_unmute_user_return_annotation(self):
        """Test that unmute_user has proper return type annotation."""
        method = getattr(MutesClient, "unmute_user")
        sig = inspect.signature(method)
        # Check return annotation exists
        assert (
            sig.return_annotation is not inspect.Signature.empty
        ), f"Method unmute_user should have return type annotation"


    def test_all_expected_methods_exist(self):
        """Test that all expected methods exist on the client."""
        expected_methods = [
            "unmute_user",
        ]
        for expected_method in expected_methods:
            assert hasattr(
                MutesClient, expected_method
            ), f"Expected method '{expected_method}' not found on MutesClient"
            assert callable(
                getattr(MutesClient, expected_method)
            ), f"'{expected_method}' exists but is not callable"
