# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
"""
Auto-generated community notes models for the X API.

This module provides Pydantic models for request and response data structures
for the community notes endpoints of the X API. All models are generated
from the OpenAPI specification and reference the canonical component schemas
in xdk.schemas, so they are fully typed.

Generated automatically - do not edit manually.
"""

from typing import Any, Dict, List, Optional, Union, Literal
from pydantic import BaseModel, Field, ConfigDict, RootModel

from .. import schemas

# Response model for search_eligible_posts
SearchEligiblePostsResponse = schemas.Get2NotesSearchPostsEligibleForNotesResponse


# Response model for delete
DeleteResponse = schemas.DeleteNoteResponse


# Request model for create
CreateRequest = schemas.CreateNoteRequest


# Response model for create
CreateResponse = schemas.CreateNoteResponse


# Request model for evaluate
EvaluateRequest = schemas.EvaluateNoteRequest


# Response model for evaluate
EvaluateResponse = schemas.EvaluateNoteResponse


# Response model for search_written
SearchWrittenResponse = schemas.Get2NotesSearchNotesWrittenResponse
