# AUTO-GENERATED FILE - DO NOT EDIT
# This file was automatically generated by the XDK build tool.
# Any manual changes will be overwritten on the next generation.
"""
Auto-generated stream module for the X API.

This module provides access to the stream endpoints of the X API
and serves as the main entry point for all stream-related functionality.

Generated automatically - do not edit manually.
"""

from .client import StreamClient

__all__ = ["StreamClient"]
